# -*- coding: utf-8 -*-
"""task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xcQOCcqQk2pqz93F7sHbMNoI8jGKQh4R
"""

import matplotlib.pyplot as plt

# Data
age_groups = ['0–20 Years', '21–40 Years', '41–60 Years', '61+ Years']
population_millions = [514, 607, 392, 149]
percentages = [34.1, 39.6, 25.7, 10.6]

# Colors to match the slide
colors = ['#FDD835', '#1976D2', '#EC407A', '#9E9E9E']  # yellow, blue, pink, grey

# Plot
plt.figure(figsize=(8, 6))
bars = plt.bar(age_groups, population_millions, color=colors, edgecolor='black')

# Add text labels (percentage + million)
for bar, pct, pop in zip(bars, percentages, population_millions):
    plt.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 10,
             f'{pct}%\n({pop}M)', ha='center', va='bottom', fontsize=10, fontweight='bold')

# Title and labels
plt.title("India's Population Distribution by Age in 2022", fontsize=14, fontweight='bold')
plt.xlabel('Age Groups', fontsize=12)
plt.ylabel('Population (in Millions)', fontsize=12)

# Add caption (optional)
plt.text(0.5, -40, 'Population ≈ 1.2 Billion | Median Age: 28',
         ha='center', fontsize=10, color='gray')

# Neat layout
plt.tight_layout()
plt.show()